---
os:
  macos:
    - macos
    - darwin
    - mac
    - apple
  linux:
    - linux
  windows:
    - windows
  freebsd:
    - freebsd
arch:
  x86_64:
    - x86_64
    - amd64
    - amd
    - intel
  aarch64:
    - aarch64
    - arm64
    - m1
