---
kind: pipeline
type: kubernetes
name: Containeraztion latest
steps:
- name: Docker build
  resources:
    limits:
      cpu: 100
      memory: 2048MiB
  when:
   branch:
     - main
  privileged: true
  settings:
    registry: git.badhouseplants.net
    username: allanger
    password: 
      from_secret: GITEA_TOKEN
    repo: git.badhouseplants.net/badhouseplants/clever-install
    tags: latest
    platforms: 
      - linux/arm64
      - linux/amd64

steps:
- name: Docker build
  image: thegeeklab/drone-docker-buildx
  trigger:
    event:
      - tag
  resources:
    limits:
      cpu: 100
      memory: 2048MiB
  privileged: true
  settings:
    registry: git.badhouseplants.net
    username: allanger
    password: 
      from_secret: GITEA_TOKEN
    repo: git.badhouseplants.net/badhouseplants/clever-install
    tags: latest
    platforms: 
      - linux/arm64
      - linux/amd64
